# Site settings
title: Minio
banner: Minimal Object Storage
email: hello@minio.io
url: https://minio.io
description: "Minimal Object Storage"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5882FA
  secondary: 233140
  secondary-dark:  151515 #A2122F

# Footer settings
footer:
  copyright: Minio.io
  location: Address

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Twitter
    url: http://twitter.com/minio_io
  - title: facebook
    url: https://www.facebook.com/Minio.io
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/minio
  - title: Quora
    url: https://www.quora.com/Minio
  - title: Github
    url: http://minio.github.io

# Postal address (add as many lines as necessary)
address:
  - line: 30 Fox Hill Rd
  - line: Woodside, CA 94062

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
